services:

  mj-mysql:
    container_name: mj-mysql
    image: mysql:8.0.44-debian
    environment:
      - MYSQL_ROOT_PASSWORD=q
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mj-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mj_network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent" ]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 20s

  messen-j:
    container_name: messen-j
    image: docker.dev.svistoyanov.com/messen-j:${MJ_VERSION}
    mem_limit: 1G
    mem_reservation: 256M
    environment:
      - DEBUG=${DEBUG}
      - JAVA_OPTS=${JAVA_OPTS}
      - PROFILE=${PROFILE}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: bind
        source: /home/svilen/docker/runtime/logs/dev/messen-j
        target: /runtime/logs
    ports:
      - "8787:8787"
      - "8080:8080"
    networks:
      - mj_network
    depends_on:
      mj-mysql:
        condition: service_healthy

networks:
  mj_network:

volumes:
  mj-mysql:
